export const ROLES = {
  ADMIN: 'ADMINISTRADOR',
  DOCENTE: 'DOCENTE',
  ESTUDIANTE: 'ESTUDIANTE'
};

export const ESTADOS_CURSO = {
  ACTIVO: 'ACTIVO',
  CANCELADO: 'CANCELADO',
  FINALIZADO: 'FINALIZADO'
};

export const ESTADOS_MATERIA = {
  ACTIVA: 'ACTIVA',
  INACTIVA: 'INACTIVA'
};